Add files via upload
ApertureDevelopment/gi-lam-project pull request #1
Opened 2024-06-18 20:27 UTC by Asdboot

2024-06-18 20:41 UTC, ApertureDevelopment requested changes
Die aufgaben bitte nicht als Batch hochladen sondern in ihre respektiven Datein packen ( unterordner `Tasks`

2024-06-18 20:41 UTC, ApertureDevelopment commented on GruppenProjekt.py
> +    zähler = 0
Es ist nicht nötig einen extra zähler mitlaufen zu lassen da es eine von python zur verfügung gestellte funktion gibt um die anzahl zu ermitteln
https://www.w3schools.com/python/gloss_python_array_length.asp

2024-06-18 20:41 UTC, ApertureDevelopment commented on GruppenProjekt.py
> +    zähler = 0
Das selbe wie oben

2024-06-18 20:44 UTC, ApertureDevelopment requested changes

2024-06-18 20:44 UTC, ApertureDevelopment commented on GruppenProjekt.py
> +    y = liste[0]
Bitte sinnvolle variablen namen verwenden

2024-06-19 10:33 UTC, Asdboot commented
Ja wird gemacht

2024-06-21 17:50 UTC, closed without merging